### ISSUE TITLE
Issue loading and saving 'true_color' with MODIS data

### ISSUE THREAD

**Issue by andyprata** [pytroll/satpy#132]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from satpy.utils import debug_on; debug_on()
from glob import glob
from satpy.scene import Scene

ppp_config_directory = "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/"
fnames = glob("/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD*hdf")
path_output = '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/'
scn = Scene(platform_name="EOS-Terra",
            sensor="modis",
            filenames=fnames,
            reader='hdfeos_l1b',
            ppp_config_dir=ppp_config_directory)
rgb_composite = 'true_color'
scn.load([rgb_composite])
scn.save_dataset(rgb_composite, path_output+rgb_composite+'.png')

```
#### Problem description
Based on the debug output I think the issue is something to do with resampling the RGB bands.
#### Expected Output
Rayleigh-corrected true color image.
#### Actual Result, Traceback if applicable
```[DEBUG: 2017-12-19 15:21:55 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/'
[DEBUG: 2017-12-19 15:21:55 : satpy.readers] Reading ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml']
[DEBUG: 2017-12-19 15:21:56 : satpy.readers.yaml_reader] Assigning to hdfeos_l1b: ['/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD03.A2017343.0145.061.2017343070358.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD021KM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02QKM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02HKM.A2017343.0145.061.2017343133022.hdf']
[DEBUG: 2017-12-19 15:21:57 : satpy.composites] Looking for composites config file modis.yaml
[DEBUG: 2017-12-19 15:21:57 : satpy.composites] Looking for composites config file visir.yaml
[DEBUG: 2017-12-19 15:21:57 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-19 15:21:57 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-19 15:21:57 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-19 15:21:57 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-19 15:21:59 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-19 15:21:59 : satpy.composites] Interpolating coszen calculations for higher resolution band
[DEBUG: 2017-12-19 15:21:59 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-19 15:22:00 : satpy.composites] Sun-zenith correction applied. Computation time:   1.3 (sec)
[DEBUG: 2017-12-19 15:22:00 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-19 15:22:00 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-19 15:22:00 : satpy.composites] Sun-zenith correction applied. Computation time:   0.2 (sec)
[WARNING: 2017-12-19 15:22:00 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-19 15:22:00 : satpy.scene] Delaying generation of DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None) because of dependency's delayed generation: DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))
[WARNING: 2017-12-19 15:22:00 : satpy.scene] Missing prerequisite for 'DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)': 'DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))'
[DEBUG: 2017-12-19 15:22:00 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-19 15:22:00 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-19 15:22:01 : satpy.composites] Sun-zenith correction applied. Computation time:   0.3 (sec)
[INFO: 2017-12-19 15:22:01 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-19 15:22:01 : pyspectral.rayleigh] Atmosphere chosen: midlatitude summer
[DEBUG: 2017-12-19 15:22:01 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/rayleigh_only/rayleigh_lut_midlatitude_summer.h5
[DEBUG: 2017-12-19 15:22:01 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-19 15:22:01 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-19 15:22:02 : pyspectral.rayleigh] Time - Interpolation: 0.130395
[DEBUG: 2017-12-19 15:22:02 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-19 15:22:02 : satpy.composites] Interpolating coszen calculations for higher resolution band
[DEBUG: 2017-12-19 15:22:02 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-19 15:22:03 : satpy.composites] Sun-zenith correction applied. Computation time:   1.2 (sec)
[WARNING: 2017-12-19 15:22:03 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-19 15:22:03 : satpy.scene] Delaying generation of DatasetID(name='4', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-19 15:22:03 : satpy.scene] The following datasets were not created: DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2481, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/py3compat.py", line 289, in execfile
    builtin_mod.execfile(filename, *where)
  File "/Users/andyprata/PycharmProjects/himawari/src/plot_modis.py", line 39, in <module>
    scn.save_dataset(rgb_composite, path_output+rgb_composite+'.png')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/scene.py", line 622, in save_dataset
    writer.save_dataset(self[dataset_id],
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/scene.py", line 303, in __getitem__
    return self.datasets[key]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/readers/__init__.py", line 182, in __getitem__
    raise KeyError("No dataset matching '{}' found".format(str(item)))
KeyError: "No dataset matching 'true_color' found"
```
#### Versions of Python, package at hand and relevant dependencies
Python version: 2.7.14
NumPy version: 1.13.1

**Comment by mraspaud** [comment]
@andyprata What you see is the result of not resampling actually :)

What happens is that the different bands from Modis are read in their original resolution, but can't be combined into a truecolor composite due to, well, having different resolutions. So satpy delays the creation of the composite, with hope that the user will resample the scene. When the resampling is done, the composite would be created. However, in your case, no resampling is performed, so at the save stage, the truecolor composite can't be found...

**Comment by andyprata** [comment]
@mraspaud Thanks for the explanation. I tried resampling using an area definition that I know is contained within the MODIS swath:
```python
rgb_composite = 'true_color'
scn.load([rgb_composite])
lcn = scn.resample("nt_fire")
lcn.save_dataset(rgb_composite, path_output+rgb_composite+'.png')
```
and I get the following error:
```
[DEBUG: 2017-12-20 09:48:23 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/'
[DEBUG: 2017-12-20 09:48:23 : satpy.readers] Reading ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml']
[DEBUG: 2017-12-20 09:48:24 : satpy.readers.yaml_reader] Assigning to hdfeos_l1b: ['/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD03.A2017343.0145.061.2017343070358.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD021KM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02QKM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02HKM.A2017343.0145.061.2017343133022.hdf']
[DEBUG: 2017-12-20 09:48:25 : satpy.composites] Looking for composites config file modis.yaml
[DEBUG: 2017-12-20 09:48:25 : satpy.composites] Looking for composites config file visir.yaml
[DEBUG: 2017-12-20 09:48:25 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 09:48:25 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 09:48:25 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 09:48:25 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 09:48:27 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 09:48:27 : satpy.composites] Interpolating coszen calculations for higher resolution band
[DEBUG: 2017-12-20 09:48:28 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 09:48:29 : satpy.composites] Sun-zenith correction applied. Computation time:   1.3 (sec)
[DEBUG: 2017-12-20 09:48:29 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 09:48:29 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 09:48:29 : satpy.composites] Sun-zenith correction applied. Computation time:   0.2 (sec)
[WARNING: 2017-12-20 09:48:29 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-20 09:48:29 : satpy.scene] Delaying generation of DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None) because of dependency's delayed generation: DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))
[WARNING: 2017-12-20 09:48:29 : satpy.scene] Missing prerequisite for 'DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)': 'DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))'
[DEBUG: 2017-12-20 09:48:29 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 09:48:29 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 09:48:29 : satpy.composites] Sun-zenith correction applied. Computation time:   0.3 (sec)
[INFO: 2017-12-20 09:48:29 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-20 09:48:29 : pyspectral.rayleigh] Atmosphere chosen: midlatitude summer
[DEBUG: 2017-12-20 09:48:29 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/rayleigh_only/rayleigh_lut_midlatitude_summer.h5
[DEBUG: 2017-12-20 09:48:29 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 09:48:29 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 09:48:30 : pyspectral.rayleigh] Time - Interpolation: 0.113686
[DEBUG: 2017-12-20 09:48:30 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 09:48:30 : satpy.composites] Interpolating coszen calculations for higher resolution band
[DEBUG: 2017-12-20 09:48:30 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 09:48:31 : satpy.composites] Sun-zenith correction applied. Computation time:   1.3 (sec)
[WARNING: 2017-12-20 09:48:31 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-20 09:48:31 : satpy.scene] Delaying generation of DatasetID(name='4', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-20 09:48:31 : satpy.scene] The following datasets were not created: DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)
[DEBUG: 2017-12-20 09:48:31 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc'
[INFO: 2017-12-20 09:48:31 : satpy.readers] Not enough information provided to find readers.
[DEBUG: 2017-12-20 09:48:31 : satpy.scene] Resampling DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 09:48:31 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 09:48:31 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-20 09:48:31 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 09:48:31 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-20 09:48:32 : satpy.scene] Resampling DatasetID(name='4', wavelength=(0.545, 0.555, 0.565), resolution=500, polarization=None, calibration=None, modifiers=('sunz_corrected',))
[DEBUG: 2017-12-20 09:48:32 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 09:48:32 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-20 09:48:32 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 09:48:32 : satpy.resample] Loaded kd-tree parameters
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2481, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/py3compat.py", line 289, in execfile
    builtin_mod.execfile(filename, *where)
  File "/Users/andyprata/PycharmProjects/himawari/src/plot_modis.py", line 37, in <module>
    lcn = scn.resample("nt_fire")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/scene.py", line 558, in resample
    **resample_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/dataset.py", line 572, in resample
    new_data = resample(source_area, data, destination_area, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/resample.py", line 521, in resample
    return resampler.resample(data, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/resample.py", line 174, in resample
    return self.compute(data, cache_id=cache_id, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/resample.py", line 295, in compute
    with_uncert=with_uncert)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyresample/kd_tree.py", line 632, in get_sample_from_neighbour_info
    raise ValueError('Mismatch between geometry and dataset')
ValueError: Mismatch between geometry and dataset
```
Here's the area definition for reference:
```
REGION: nt_fire {
	NAME:	nt_fire
	PCS_ID:	merc_134.5_-17.5
	PCS_DEF:	proj=merc,lat_0=-17.5,lon_0=134.5,ellps=WGS84
	XSIZE:	557
	YSIZE:	580
	AREA_EXTENT:	(-278298.7269831836, -2258423.6490963777, 278298.7269831836, -1678147.5163917774)
};
```

**Comment by mraspaud** [comment]
@andyprata I think I fixed your issue, could you try out the latest develop branch from github ?

**Comment by andyprata** [comment]
@mraspaud Thanks for looking into this. It got a bit further this time but still ends in an error. Here's the output:
```
[DEBUG: 2017-12-20 22:08:34 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/'
[DEBUG: 2017-12-20 22:08:34 : satpy.readers] Reading ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml']
[DEBUG: 2017-12-20 22:08:34 : satpy.readers.yaml_reader] Assigning to hdfeos_l1b: ['/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD03.A2017343.0145.061.2017343070358.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD021KM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02QKM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02HKM.A2017343.0145.061.2017343133022.hdf']
[DEBUG: 2017-12-20 22:08:35 : satpy.composites] Looking for composites config file modis.yaml
[DEBUG: 2017-12-20 22:08:35 : satpy.composites] Looking for composites config file visir.yaml
[DEBUG: 2017-12-20 22:08:35 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:08:35 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:08:35 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:08:36 : satpy.readers.hdfeos_l1b] Interpolating from 1000 to 500
[DEBUG: 2017-12-20 22:09:23 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:09:25 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 22:09:25 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 22:09:26 : satpy.composites] Sun-zenith correction applied. Computation time:   1.2 (sec)
[DEBUG: 2017-12-20 22:09:26 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 22:09:26 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 22:09:26 : satpy.composites] Sun-zenith correction applied. Computation time:   0.4 (sec)
[WARNING: 2017-12-20 22:09:26 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-20 22:09:26 : satpy.scene] Delaying generation of DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None) because of dependency's delayed generation: DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))
[WARNING: 2017-12-20 22:09:26 : satpy.scene] Missing prerequisite for 'DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)': 'DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))'
[DEBUG: 2017-12-20 22:09:26 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 22:09:26 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 22:09:27 : satpy.composites] Sun-zenith correction applied. Computation time:   0.3 (sec)
[INFO: 2017-12-20 22:09:27 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-20 22:09:27 : pyspectral.rayleigh] Atmosphere chosen: us-standard
[DEBUG: 2017-12-20 22:09:27 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/marine_clean_aerosol/rayleigh_lut_us-standard.h5
[DEBUG: 2017-12-20 22:09:27 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 22:09:27 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 22:09:28 : pyspectral.rayleigh] Time - Interpolation: 0.121532
[DEBUG: 2017-12-20 22:09:28 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-20 22:09:28 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-20 22:09:29 : satpy.composites] Sun-zenith correction applied. Computation time:   1.5 (sec)
[WARNING: 2017-12-20 22:09:29 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-20 22:09:29 : satpy.scene] Delaying generation of DatasetID(name='4', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-20 22:09:29 : satpy.scene] The following datasets were not created: DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc'
[INFO: 2017-12-20 22:09:30 : satpy.readers] Not enough information provided to find readers.
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Resampling DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:09:30 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Resampling DatasetID(name='4', wavelength=(0.545, 0.555, 0.565), resolution=500, polarization=None, calibration=None, modifiers=('sunz_corrected',))
[DEBUG: 2017-12-20 22:09:30 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area modis_4060_2708_longitude_latitude
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Resampling DatasetID(name='solar_azimuth_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:09:30 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Resampling DatasetID(name='9', wavelength=(0.438, 0.443, 0.448), resolution=1000, polarization=None, calibration=None, modifiers=('sunz_corrected',))
[DEBUG: 2017-12-20 22:09:30 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Copying source area to mask invalid dataset points
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Resampling DatasetID(name='satellite_zenith_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:09:30 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Resampling DatasetID(name='1', wavelength=(0.62, 0.645, 0.67), resolution=500, polarization=None, calibration='reflectance', modifiers=('sunz_corrected',))
[DEBUG: 2017-12-20 22:09:30 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area modis_4060_2708_longitude_latitude
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-20 22:09:30 : satpy.scene] Resampling DatasetID(name='solar_zenith_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-20 22:09:30 : satpy.config] Read config from ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/satpy.cfg']
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Computing kd-tree hash for area nt_fire
[DEBUG: 2017-12-20 22:09:30 : satpy.resample] Loaded kd-tree parameters
[INFO: 2017-12-20 22:09:30 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-20 22:09:30 : pyspectral.rayleigh] Atmosphere chosen: us-standard
[DEBUG: 2017-12-20 22:09:30 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/marine_clean_aerosol/rayleigh_lut_us-standard.h5
[DEBUG: 2017-12-20 22:09:30 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 22:09:30 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 22:09:31 : pyspectral.rayleigh] Time - Interpolation: 0.011417
[INFO: 2017-12-20 22:09:31 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-20 22:09:31 : pyspectral.rayleigh] Atmosphere chosen: us-standard
[DEBUG: 2017-12-20 22:09:31 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/marine_clean_aerosol/rayleigh_lut_us-standard.h5
[DEBUG: 2017-12-20 22:09:31 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 22:09:31 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-20 22:09:31 : pyspectral.rayleigh] Time - Interpolation: 0.009875
[WARNING: 2017-12-20 22:09:31 : satpy.scene] Missing prerequisite for 'DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration=None, modifiers=('sunz_corrected',))': 'DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration=None, modifiers=())'
[WARNING: 2017-12-20 22:09:31 : satpy.scene] Missing prerequisite for 'DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))': 'DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration=None, modifiers=('sunz_corrected',))'
[WARNING: 2017-12-20 22:09:31 : satpy.scene] Missing prerequisite for 'DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)': 'DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))'
[WARNING: 2017-12-20 22:09:31 : satpy.scene] The following datasets were not created: DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2481, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/py3compat.py", line 289, in execfile
    builtin_mod.execfile(filename, *where)
  File "/Users/andyprata/PycharmProjects/himawari/src/plot_modis.py", line 40, in <module>
    lcn.save_dataset(rgb_composite, path_output+rgb_composite+'.png')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/scene.py", line 623, in save_dataset
    writer.save_dataset(self[dataset_id],
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/scene.py", line 304, in __getitem__
    return self.datasets[key]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/readers/__init__.py", line 183, in __getitem__
    raise KeyError("No dataset matching '{}' found".format(str(item)))
KeyError: "No dataset matching 'true_color' found"
```

**Comment by howff** [comment]
Andy, your pass is at 0145, is it possible to produce true_color at night?

**Comment by andyprata** [comment]
@howff Northern Territory (Australia) timezone is UTC+9:30 so 01:45 UTC is 11:15 am LT.

**Comment by mraspaud** [comment]
@andyprata would it be possible for you to share your data so that I can test on it ?

**Comment by andyprata** [comment]
@mraspaud Sure. You should be able to wget the files from these links:
```
ftp://ladsweb.nascom.nasa.gov/allData/61/MOD021KM/2017/343/MOD021KM.A2017343.0145.061.2017343133022.hdf
ftp://ladsweb.nascom.nasa.gov/allData/61/MOD02HKM/2017/343/MOD02HKM.A2017343.0145.061.2017343133022.hdf
ftp://ladsweb.nascom.nasa.gov/allData/61/MOD02QKM/2017/343/MOD02QKM.A2017343.0145.061.2017343133022.hdf
ftp://ladsweb.nascom.nasa.gov/allData/61/MOD03/2017/343/MOD03.A2017343.0145.061.2017343070358.hdf
```

**Comment by davidh-ssec** [comment]
@mraspaud This makes me think we need to add a utility method on the Scene for check if all datasets were loaded/created.

**Comment by davidh-ssec** [comment]
@andyprata It looks like you've uncovered multiple bugs so good job. First, @mraspaud and some others are having difficulty reproducing your issue because there is a bug in the dependency finding that is automatically loading 1000m resolution data for him, but not for me and you.

The second bug is that it seems like the hdfeos_l1b reader (modis reader) doesn't handle multiple resolutions properly so it says that the 250m resolution is available when it isn't.

The third bug which may be solved the the above fixes is that for certain people we get exceptions with the newest versions of every package when trying to interpolate from 1000m to 250m: `TypeError: x must be strictly increasing`.

There may be a forth bug related to your actual error above, but at this point we'll have to see what happens after the above bugs are fixed.

**Comment by mraspaud** [comment]
@andyprata looks like bugs 1, 2, and 3 are now fixed thanks to @davidh-ssec , and I successfully generated a resampled image from you modis data. Feel free to get the changes from #138 to try it out !

**Comment by davidh-ssec** [comment]
Bug 2 is still an issue but it doesnt affect this if you provide all resolution files.

**Comment by andyprata** [comment]
@mraspaud @davidh-ssec I can confirm that my code now works (using the bugfix-modis-reader branch). Thanks! 

@davidh-ssec Instead of resampling is there a way I can output the entire swath at 250 m resolution? Like what you used to get when running `p2g_glue crefl` on MODIS data?

**Comment by davidh-ssec** [comment]
@andyprata We've (@mraspaud, @adybbroe, and I) have been talking about that. With Polar2Grid it is doing resampling to get the actual true color RGB. One option as a workaround for you would be to do `scn.resample(scn['1'].info['area'])` which should resample all lower resolution bands to the same resolution at the sensor's native projection and then compute the `true_color` composite.

If I'm missing something about your p2g comment, let me know.

**Comment by andyprata** [comment]
@davidh-ssec Thanks - that's exactly what I was after. However, I get an error when I do `scn.resample(scn['1'].info['area'])`. Here's the Traceback:
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2481, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/py3compat.py", line 289, in execfile
    builtin_mod.execfile(filename, *where)
  File "/Users/andyprata/PycharmProjects/himawari/src/plot_modis.py", line 38, in <module>
    lcn = scn.resample(scn['1'].info['area'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/scene.py", line 559, in resample
    **resample_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/dataset.py", line 572, in resample
    new_data = resample(source_area, data, destination_area, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/resample.py", line 521, in resample
    return resampler.resample(data, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/resample.py", line 174, in resample
    return self.compute(data, cache_id=cache_id, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/resample.py", line 295, in compute
    with_uncert=with_uncert)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyresample/kd_tree.py", line 636, in get_sample_from_neighbour_info
    valid_output_size = valid_output_index.sum()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/ma/core.py", line 4982, in sum
    _mask = self._mask
AttributeError: 'Dataset' object has no attribute '_mask'
```

**Comment by davidh-ssec** [comment]
It is unlucky that you keep finding all these bugs. However you are in luck because I also get that error and am in the process of debugging it.

**Comment by davidh-ssec** [comment]
@mraspaud I found a solution to this, but I'm not sure my solution is the best. Line 369 of `pyresample/kd_tree.py` I replace with:

```
                if isinstance(valid_output_index, np.ma.MaskedArray):
                    valid_output_index = np.ma.append(valid_output_index, next_voi)
                else:
                    valid_output_index = np.append(valid_output_index, next_voi)
```

It used to be just the `np.append` which with the target area being a SwathDefinition in this case and now that lons/lats are `Dataset` objects (read: Masked Arrays) it causes a weird interaction where the result of the append is a `Dataset` but it doesn't have a `_mask` attribute. With the above change it is a proper masked array. **However**, it is an index array so there is no point in anything being masked and there is no proper `valid_output_index.filled(invalid_index_value)`. I'm writing this down so that any future fixes I make make sense. I'll continue looking for the right fix.

**Comment by andyprata** [comment]
@davidh-ssec I've found a workaround but it's a bit awkward. I've used the coord2area_def.py utility to generate an area definition 'region' using the MODIS lat/lon limits. Then I copied the area definition into areas.def and resampled. It works but is obviously a pain to have to do for every new MODIS granule. 

Maybe something like this would be better:
```
lons, lats = scn['1'].info['area'].get_lonlats()
res = 0.25 # 250 m resolution
proj = 'merc' # mercator projection
modis_def = create_def(proj, lats.min(), lats.max(), lons.min(), lons.max(), res)
lcn = scn.resample(modis_def)
```
Is there a function like `create_def` that already exists within pytroll/satpy?
I will try your solution now as well.

**Comment by davidh-ssec** [comment]
@andyprata I have a solution that I'm testing out now and will push to pyresample soon. I don't think you want to do what you're doing, but it depends on what you want for your final result. Your solution is basically resampling the data to a mercator projection with dynamic extents. Pyresample recently added a DynamicAreaDefinition class that you "freeze" to a certain exact area by providing it extents and would likely do the equivalent of what you want.

You said originally that you didn't want to resample the data. Do you need it in the original swath coordinates?

**Comment by andyprata** [comment]
@davidh-ssec OK great. I will wait for your next push. In answer to your question, I usually like to view MODIS data in its original swath coordinates. However, I would also like to be able to resample as I want to compare the data with Himawari-8 (and eventually Sentinel-2).

**Comment by davidh-ssec** [comment]
Resampling to the native projection should work although it could be made simpler. The resample call I gave you is supposed to work. Due to some changes in SatPy over the last couple months this functionality broke.

See https://github.com/pytroll/pyresample/pull/88 for my fix. If you try that branch of pyresample you *should* be able to do what we've talked about.

**Comment by andyprata** [comment]
@davidh-ssec Great. I've pulled your fix from pyresample and I now get true color output in original swath coordinates (like those provided on MODIS [rapidfire](rapidfire.sci.gsfc.nasa.gov/realtime/)) - thanks.

I had a look at the DynamicAreaDefinition class and the freeze function you mentioned but can't figure out how to implement it. I wanted to see if I could reproduce the result from the following polar2grid call but using SatPy:
```
p2g_glue crefl gtiff true_color --true-color -f MO*.hdf
```
Does p2g resample to Mercator?

**Comment by mraspaud** [comment]
@andyprata I'm not familiar with p2g, but regarding dynamic area definitions, you can do something like this:
```python
from satpy.utils import debug_on; debug_on()
from glob import glob
from satpy.scene import Scene

fnames = glob("/home/a001673/data/satellite/MOD*A2017*hdf")
path_output = './'
scn = Scene(platform_name="EOS-Terra",
            sensor="modis",
            filenames=fnames,
            reader='hdfeos_l1b')
rgb_composite = '20'
scn.load([rgb_composite])


from pyresample.geometry import DynamicAreaDefinition

area = DynamicAreaDefinition('mercator', 
                             'Mercator Bounding Box for Polar Overpasses', 
                             {'proj': 'merc', 'ellps': 'WGS84'})

area = area.freeze(scn[rgb_composite].info['area'], resolution=1000)

newscn = scn.resample(area)
newscn.show(rgb_composite)
```

**Comment by davidh-ssec** [comment]
The default grid for geotiff creation in P2G is a dynamic uniform latlong grid (https://github.com/davidh-ssec/polar2grid/blob/develop/polar2grid/grids/grids.conf#L6). So to do that in SatPy you could probably take Martin's example and change the area definition to have `'proj': 'latlong'` and probably change the resolution to be in degrees (@mraspaud)?

**Comment by andyprata** [comment]
@mraspaud Thanks for the code. @davidh-ssec I tried using `'proj': 'latlong'` but all I get is an empty tiff file as the output. @mraspaud's code works fine for me for now. 

I would just note a few differences between the output of p2g and satpy (using 'merc' proj):
1) There are some strange effects at the swath edges for the satpy output - it's like the edges have been stretched too far outside the swath bounds
2) The tiff output from satpy results in significantly larger files than p2g (130 MB vs 25 MB)
3) There are some strange shading artefacts on cloud in some parts of the satpy image.

I can attach screenshots if you'd like to look into this further but I'm happy to leave it for now.

Thanks again for all your help on this!

**Comment by howff** [comment]
File size: either sample size or compression; you can use tiffinfo and gdalinfo to find out.

Artefacts: I would be interested to see the differences visually.

**Comment by davidh-ssec** [comment]
@andyprata Polar2Grid and SatPy don't use the same defaults, but most things should be possible in SatPy that are possible in P2G.

1. This is due to your `radius_of_influence` when using resampling. It allows the swath pixels to have influence further than the actual footprint. For nearest neighbor resampling (the default), you have to balance this edge effect and the possibility of missing pixels in the final image. It is not heavily tested in SatPy yet but you can choose `method='ewa'` to use the same resampling that P2G uses.

2. Like @howff said this is likely due to compression not being the default in SatPy. Use `compress='lzw'` and you should get better file sizes.

3. Could you provide screenshots of these? It is likely because a lot of the enhancements used by P2G are not in SatPy yet.

**Comment by andyprata** [comment]
@davidh-ssec @howff Thanks for the responses. @davidh-ssec I tried your suggestions but not sure if I've got the code right:
```python
rgb_composite = 'true_color'
scn.load([rgb_composite])
area = DynamicAreaDefinition('mercator',
                             'Mercator Bounding Box for Polar Overpasses',
                             {'proj': 'merc', 'ellps': 'WGS84'})
area = area.freeze(scn['1'].info['area'], resolution=250)
lcn = scn.resample(area, method='ewa')
lcn.save_dataset(rgb_composite, path_output+rgb_composite+'.tif', compress='lzw')
```
This code results in a ~220 MB tiff with the same effects I described before. To show you what I'm talking about I've attached 3 images: P2G and SatPy output (file sizes have been reduced using ImageMagick; `convert input.tif -resize 6000 output.jpg`) and an annotated screenshot noting the differences between the two. I also noticed that the swath edges were cropped in the SatPy output.
![true_color_p2g](https://user-images.githubusercontent.com/8485285/34350658-18e0365e-ea6c-11e7-997b-f30f313c6f49.jpg)
![true_color_satpy](https://user-images.githubusercontent.com/8485285/34350666-284d1a44-ea6c-11e7-8ddd-bfeea9ab1be3.jpg)
![satpy_vs_p2g](https://user-images.githubusercontent.com/8485285/34350680-3bd5d8c6-ea6c-11e7-870b-ce22d60ca351.png)

**Comment by davidh-ssec** [comment]
@andyprata 

1. Do you get different sized files with/without the compress flag?
2. Could you try `from satpy.utils import debug_on; debug_on()` before all your other code and check if the resample call is actually running nearest neighbor or if it is actually running EWA?
3. I don't have a good idea about the shadowing artifacts, but it definitely looks like nearest neighbor is still being used given the edge effects. Or it's possible that the EWA parameters are defaulting to something not good for MODIS.

**Comment by andyprata** [comment]
@davidh-ssec 
1. Yes - `compress='lzw'` in the `save_dataset` method results in a ~220 MB tiff. Without this flag I get a ~130 MB tiff.
2. Here's the debug output. I wasn't sure what to look for but I've put a print statement (`Resampling data...`) just before the resample call (`lcn = scn.resample(area, method='ewa')`) :
```
[DEBUG: 2017-12-27 16:25:25 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/'
[DEBUG: 2017-12-27 16:25:25 : satpy.readers] Reading ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc/readers/hdfeos_l1b.yaml']
[DEBUG: 2017-12-27 16:25:25 : satpy.readers.yaml_reader] Assigning to hdfeos_l1b: ['/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD03.A2017343.0145.061.2017343070358.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD021KM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02QKM.A2017343.0145.061.2017343133022.hdf', '/Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/MOD02HKM.A2017343.0145.061.2017343133022.hdf']
[DEBUG: 2017-12-27 16:25:26 : satpy.composites] Looking for composites config file modis.yaml
[DEBUG: 2017-12-27 16:25:26 : satpy.composites] Looking for composites config file visir.yaml
[DEBUG: 2017-12-27 16:25:26 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=250, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:25:27 : satpy.readers.hdfeos_l1b] Interpolating from 1000 to 250
[DEBUG: 2017-12-27 16:28:13 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:28:13 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:28:13 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:28:14 : satpy.readers.hdfeos_l1b] Interpolating from 1000 to 500
[DEBUG: 2017-12-27 16:29:00 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=250, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:29:00 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=500, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:29:05 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-27 16:29:05 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-27 16:29:12 : satpy.composites] Sun-zenith correction applied. Computation time:   7.3 (sec)
[DEBUG: 2017-12-27 16:29:12 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-27 16:29:12 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-27 16:29:12 : satpy.composites] Sun-zenith correction applied. Computation time:   0.3 (sec)
[WARNING: 2017-12-27 16:29:12 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-27 16:29:12 : satpy.scene] Delaying generation of DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None) because of dependency's delayed generation: DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))
[WARNING: 2017-12-27 16:29:12 : satpy.scene] Missing prerequisite for 'DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)': 'DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected'))'
[DEBUG: 2017-12-27 16:29:12 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-27 16:29:13 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-27 16:29:14 : satpy.composites] Sun-zenith correction applied. Computation time:   1.7 (sec)
[WARNING: 2017-12-27 16:29:14 : satpy.scene] Delaying generation of DatasetID(name='3', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[DEBUG: 2017-12-27 16:29:14 : satpy.composites] Applying sun zen correction
[DEBUG: 2017-12-27 16:29:14 : satpy.composites] Apply the standard sun-zenith correction [1/cos(sunz)]
[DEBUG: 2017-12-27 16:29:15 : satpy.composites] Sun-zenith correction applied. Computation time:   1.3 (sec)
[WARNING: 2017-12-27 16:29:15 : satpy.scene] Delaying generation of DatasetID(name='1', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-27 16:29:15 : satpy.scene] Delaying generation of DatasetID(name='4', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=('sunz_corrected', 'rayleigh_corrected')) because of incompatible areas
[WARNING: 2017-12-27 16:29:15 : satpy.scene] The following datasets were not created: DatasetID(name='true_color', wavelength=None, resolution=None, polarization=None, calibration=None, modifiers=None)
Resampling data...
[DEBUG: 2017-12-27 16:29:22 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.6-py2.7.egg/satpy/etc'
[INFO: 2017-12-27 16:29:22 : satpy.readers] Not enough information provided to find readers.
[DEBUG: 2017-12-27 16:29:22 : satpy.scene] Resampling DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=500, polarization=None, calibration=None, modifiers=('sunz_corrected',))
[DEBUG: 2017-12-27 16:29:22 : satpy.resample] Computing kd-tree hash for area modis_4060_2708_longitude_latitude
[DEBUG: 2017-12-27 16:29:22 : satpy.resample] Computing kd-tree hash for area Mercator Bounding Box for Polar Overpasses
[DEBUG: 2017-12-27 16:29:22 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-27 16:29:31 : satpy.scene] Resampling DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:29:31 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-27 16:29:31 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-27 16:29:42 : satpy.scene] Resampling DatasetID(name='4', wavelength=(0.545, 0.555, 0.565), resolution=500, polarization=None, calibration=None, modifiers=('sunz_corrected',))
[DEBUG: 2017-12-27 16:29:42 : satpy.resample] Computing kd-tree hash for area modis_4060_2708_longitude_latitude
[DEBUG: 2017-12-27 16:29:42 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-27 16:29:50 : satpy.scene] Resampling DatasetID(name='1', wavelength=(0.62, 0.645, 0.67), resolution=250, polarization=None, calibration='reflectance', modifiers=('sunz_corrected',))
[DEBUG: 2017-12-27 16:29:50 : satpy.resample] Computing kd-tree hash for area modis_8120_5416_longitude_latitude
[DEBUG: 2017-12-27 16:29:51 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-27 16:30:04 : satpy.scene] Resampling DatasetID(name='9', wavelength=(0.438, 0.443, 0.448), resolution=1000, polarization=None, calibration=None, modifiers=('sunz_corrected',))
[DEBUG: 2017-12-27 16:30:04 : satpy.resample] Copying source area to mask invalid dataset points
[DEBUG: 2017-12-27 16:30:05 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-27 16:30:05 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-27 16:30:15 : satpy.scene] Resampling DatasetID(name='satellite_zenith_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:30:15 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-27 16:30:15 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-27 16:30:24 : satpy.scene] Resampling DatasetID(name='solar_zenith_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:30:24 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-27 16:30:24 : satpy.resample] Loaded kd-tree parameters
[DEBUG: 2017-12-27 16:30:34 : satpy.scene] Resampling DatasetID(name='solar_azimuth_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-12-27 16:30:34 : satpy.resample] Computing kd-tree hash for area modis_2030_1354_longitude_latitude
[DEBUG: 2017-12-27 16:30:34 : satpy.resample] Loaded kd-tree parameters
[INFO: 2017-12-27 16:30:44 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-27 16:30:53 : pyspectral.rayleigh] Atmosphere chosen: us-standard
[DEBUG: 2017-12-27 16:30:53 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/marine_clean_aerosol/rayleigh_lut_us-standard.h5
[DEBUG: 2017-12-27 16:30:53 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-27 16:30:53 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-27 16:31:32 : pyspectral.rayleigh] Time - Interpolation: 19.188734
[INFO: 2017-12-27 16:31:44 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-27 16:31:50 : pyspectral.rayleigh] Atmosphere chosen: us-standard
[DEBUG: 2017-12-27 16:31:50 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/marine_clean_aerosol/rayleigh_lut_us-standard.h5
[DEBUG: 2017-12-27 16:31:50 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-27 16:31:50 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-27 16:32:25 : pyspectral.rayleigh] Time - Interpolation: 19.987673
[INFO: 2017-12-27 16:32:42 : satpy.composites] Removing Rayleigh scattering and aerosol absorption
[INFO: 2017-12-27 16:32:49 : pyspectral.rayleigh] Atmosphere chosen: us-standard
[DEBUG: 2017-12-27 16:32:49 : pyspectral.rayleigh] LUT filename: /Users/andyprata/.local/share/pyspectral/marine_clean_aerosol/rayleigh_lut_us-standard.h5
[DEBUG: 2017-12-27 16:32:50 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-27 16:32:50 : pyspectral.rsr_reader] Filename: /Users/andyprata/.local/share/pyspectral/rsr_modis_EOS-Terra.h5
[DEBUG: 2017-12-27 16:33:15 : pyspectral.rayleigh] Time - Interpolation: 13.726873
[DEBUG: 2017-12-27 16:33:50 : satpy.writers] Enhancement configuration options: [{'name': 'cira_stretch', 'method': <function cira_stretch at 0x115b74a28>}]
[DEBUG: 2017-12-27 16:33:50 : satpy.enhancements] Applying the cira-stretch
[DEBUG: 2017-12-27 16:34:29 : satpy.writers.geotiff] Saving to GeoTiff: /Users/andyprata/Documents/python/MODIS/2017_nt_fires/T20173430145/true_color_satpy_compress_lzw.tif
```

**Comment by davidh-ssec** [comment]
1. I looked at this more closely (still haven't tested anything), but the default settings for the geotiff writer are to use DEFLATE compression so it makes sense that the default would be fairly small. Additionally I am reminded that satpy defaults to using an alpha band for masking invalid values where I think I have P2G setting mask values to black. You could try passing `fill_value=(0, 0, 0)` and see if that reduces the size to something similar to P2G.
2. Definitely looks like nearest neighbor is being used. I'll try to look at this later today, but I'm kind of on vacation so no promises.

@mraspaud Do you have any idea on the resampling issues being brought up? Why the dynamic area seems to be clipping the swath or why there are the weird shadowy areas?

**Comment by mraspaud** [comment]
the fringe around the data is due to a too large `radius_of_influence` in the resampling part (it defaults to 10km, from modis in 1km resolution, 2-3 km is probably enough). The clipping shouldn't remove any of the data, it's just removing parts of the fringe actually.
The shadowy areas I believe is due to the pyspectral settings, which do correct more that crefl used in p2g. This has since been fixed in the settings to do approximately the same correction in pyspectral as is done in crefl.
